theme: minima
title: Aprender carreras por cuenta propia
author: Lal
desription: Recursos y consejos sobre cómo estudiar por cuenta propia y lograr conseguir trabajo, teniendo bajos o no recursos monetarios. 
